project:
  type: website

website:
  title: "Mano Prakash Parthasarathi"
  navbar:
    background: primary
    search: true
    left:
      - href: about.qmd
        text: About Me
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: talks.qmd
        text: Talks
      - href: cv.qmd
        text: CV
      - href: misc.qmd
        text: Misc
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/manoprakash6/
      - icon: github
        href: https://github.com/manoprakash6
format:
  html:
    theme:
      - sketchy
      - brand
    css: styles.css
    toc: true
