project:
  type: website
  output-dir: docs

website:
  title: "Mano Prakash Parthasarathi"
  navbar:
    background: primary
    search: true
    left:
      - text: About Me
        href: about/about.qmd
      - text: Research          
        href: research/research.qmd
      - text: Teaching
        href: teaching/teaching.qmd
      # - text: Talks
      #   href: talks/talks.qmd
      - text: CV
        href: cv/cv.qmd
      - text: Misc
        href: misc/misc.qmd  
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/manoprakash6/
        target: _blank
      - icon: github
        href: https://github.com/manoprakash6
        target: _blank
  google-analytics: 
    tracking-id: "{{< env GOOGLE_ANALYTICS_ID >}}"
    storage: none
format:
  html:
    theme:
      - sketchy
      - brand
    css: styles.css
    toc: true
    html-math-method: katex
    smooth-scroll: true
    anchor-sections: true
    page-layout: full
    link-external-newwindow: true
