project:
  type: website

website:
  title: "Mano Prakash Parthasarathi"
  navbar:
    background: primary
    search: true
    left:
      - href: about/about.qmd
        text: About Me
      - href: research/research.qmd
        text: Research
      - href: teaching/teaching.qmd
        text: Teaching
      - href: talks/talks.qmd
        text: Talks
      - href: cv/cv.qmd
        text: CV
      - href: misc/misc.qmd
        text: Misc
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/manoprakash6/
      - icon: github
        href: https://github.com/manoprakash6
format:
  html:
    theme:
      - sketchy
      - brand
    css: styles.css
    toc: true
    html-math-method: katex
    smooth-scroll: true
    anchor-sections: true
    page-layout: full
